/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as authenticatedImport } from './routes/__authenticated'
import { Route as authenticatedIndexImport } from './routes/__authenticated/index'
import { Route as authenticatedProfileImport } from './routes/__authenticated/profile'
import { Route as authenticatedExpensesImport } from './routes/__authenticated/expenses'
import { Route as authenticatedCreateExpenseImport } from './routes/__authenticated/create-expense'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const authenticatedRoute = authenticatedImport.update({
  id: '/__authenticated',
  getParentRoute: () => rootRoute,
} as any)

const authenticatedIndexRoute = authenticatedIndexImport.update({
  path: '/',
  getParentRoute: () => authenticatedRoute,
} as any)

const authenticatedProfileRoute = authenticatedProfileImport.update({
  path: '/profile',
  getParentRoute: () => authenticatedRoute,
} as any)

const authenticatedExpensesRoute = authenticatedExpensesImport.update({
  path: '/expenses',
  getParentRoute: () => authenticatedRoute,
} as any)

const authenticatedCreateExpenseRoute = authenticatedCreateExpenseImport.update(
  {
    path: '/create-expense',
    getParentRoute: () => authenticatedRoute,
  } as any
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__authenticated': {
      id: '/__authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/__authenticated/create-expense': {
      id: '/__authenticated/create-expense'
      path: '/create-expense'
      fullPath: '/create-expense'
      preLoaderRoute: typeof authenticatedCreateExpenseImport
      parentRoute: typeof authenticatedImport
    }
    '/__authenticated/expenses': {
      id: '/__authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof authenticatedExpensesImport
      parentRoute: typeof authenticatedImport
    }
    '/__authenticated/profile': {
      id: '/__authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof authenticatedProfileImport
      parentRoute: typeof authenticatedImport
    }
    '/__authenticated/': {
      id: '/__authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticatedIndexImport
      parentRoute: typeof authenticatedImport
    }
  }
}

// Create and export the route tree

interface authenticatedRouteChildren {
  authenticatedCreateExpenseRoute: typeof authenticatedCreateExpenseRoute
  authenticatedExpensesRoute: typeof authenticatedExpensesRoute
  authenticatedProfileRoute: typeof authenticatedProfileRoute
  authenticatedIndexRoute: typeof authenticatedIndexRoute
}

const authenticatedRouteChildren: authenticatedRouteChildren = {
  authenticatedCreateExpenseRoute: authenticatedCreateExpenseRoute,
  authenticatedExpensesRoute: authenticatedExpensesRoute,
  authenticatedProfileRoute: authenticatedProfileRoute,
  authenticatedIndexRoute: authenticatedIndexRoute,
}

const authenticatedRouteWithChildren = authenticatedRoute._addFileChildren(
  authenticatedRouteChildren
)

export interface FileRoutesByFullPath {
  '': typeof authenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/create-expense': typeof authenticatedCreateExpenseRoute
  '/expenses': typeof authenticatedExpensesRoute
  '/profile': typeof authenticatedProfileRoute
  '/': typeof authenticatedIndexRoute
}

export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/create-expense': typeof authenticatedCreateExpenseRoute
  '/expenses': typeof authenticatedExpensesRoute
  '/profile': typeof authenticatedProfileRoute
  '/': typeof authenticatedIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/__authenticated': typeof authenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/__authenticated/create-expense': typeof authenticatedCreateExpenseRoute
  '/__authenticated/expenses': typeof authenticatedExpensesRoute
  '/__authenticated/profile': typeof authenticatedProfileRoute
  '/__authenticated/': typeof authenticatedIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/about' | '/create-expense' | '/expenses' | '/profile' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/create-expense' | '/expenses' | '/profile' | '/'
  id:
    | '__root__'
    | '/__authenticated'
    | '/about'
    | '/__authenticated/create-expense'
    | '/__authenticated/expenses'
    | '/__authenticated/profile'
    | '/__authenticated/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  authenticatedRoute: typeof authenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
}

const rootRouteChildren: RootRouteChildren = {
  authenticatedRoute: authenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/__authenticated",
        "/about"
      ]
    },
    "/__authenticated": {
      "filePath": "__authenticated.tsx",
      "children": [
        "/__authenticated/create-expense",
        "/__authenticated/expenses",
        "/__authenticated/profile",
        "/__authenticated/"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/__authenticated/create-expense": {
      "filePath": "__authenticated/create-expense.tsx",
      "parent": "/__authenticated"
    },
    "/__authenticated/expenses": {
      "filePath": "__authenticated/expenses.tsx",
      "parent": "/__authenticated"
    },
    "/__authenticated/profile": {
      "filePath": "__authenticated/profile.tsx",
      "parent": "/__authenticated"
    },
    "/__authenticated/": {
      "filePath": "__authenticated/index.tsx",
      "parent": "/__authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
